stages:
  download_data:
    cmd: python src/download.py
    deps:
      - src/download.py
    outs:
      - data/raw.csv
  preprocessing:
    cmd: python src/preprocess.py
    deps:
      - data/raw.csv
      - src/preprocess.py
    outs:
      - data/scaled_df.csv
  train:
    cmd: python src/train_model.py 
    deps:
      - data/scaled_df.csv
      - src/train_model.py
    outs:
      - best_wine.pkl
